language: node_js
node_js:
- lts/*
addons:
  sonarcloud:
    organization: molgenis
    token:
      secure: bvQjauRVvqCZ++Fl2PxE873ykehRkG1+ngpDHp9K/Af1/hJUU4XNwZKYA9BeHOSxD+hELOLuYZracTzIPQ+ctWKhcQWlWmNHg3VKg6um9aUT/qMaT57tN8VoECZ54QxMY+I4Kv3f92/tdEfc/O0McCCPRmdY2pYIV/MzaMXcu3iCvEiRUk4uYO7SI/HquYdbC6WgBY5sGaC2db+wpmjrMVvol2OFylGQUHuy3fPouNsjfbAzFMNEpNEHErUVcEK/4yEw8dqT1d8eFzN9H4OM/SG9v0jMaTF+5H6zkQ3gnUUao87EEpeuh0XGrRQeGS+aMfEJjpZwFWOgrZ4vnGJwbLUyVHJIpzKXthJyvDCcreU+73gJ+gd9UJEik27koAz2ynGpbk6Y6WvATzE9fnI2FVbkw829XhO0vknwxu0R+82DKV+0JWBbKqZkDbNZ43QHRE4r5jHE4l6FWVrilBw+uBh+mOoyEGpJV3VXnwIL54A+mldwbhQNULfdfrLLty5QThKRO6erSap0gYYUJ6mSsIjro/Gtz7H/d511zeAtpgvWkbxcRXAvNI+Di0XC4INrUvnS9XdCsX3m28WKo2NCHqybnuHoyzaTD3s+vzWNua0acCmVapG3AQWDcfUQZKnYkTeoOoSe6xLDTsbD8oVk0BJ+ntPZfisquvdGGKiIM7k=
script:
  - sonar-scanner
before_deploy:
  - npm run build
deploy:
# temporarily disable for 0.0.1 github releases deploy
#  - provider: npm
#    api_token:
#      secure: TxQUU8xNTVTqhQ6pYTR+ic7Crv6rPZ7UbRo8HJJOGlFA30Vb/O36kh3Vgwx3fM5oinC1I38pzmHjJ4WVz2qiUZcgNzDHMorQhErbfSWLO8G7XTsVkMkyozPPtgdCCT2Z7FfdTKmY5an+V4ZJlreM83+vlJmUzMoGahZElESBk94QkTnPAqk46whXAf/zToEw7OJsxd2N3uPyPB8+rgg5VMApRBsCegt3KyetiMBIYWX+kJLxXEGK7OnJmxz1SGrYHR87YEDog7awBIhrXNcBWc4Lj55oWEqp3JQlpLnVDhEUCSO8cmQkyIMTYZ3eIKoyrDk9vfAYYbDsRvagFXKTZGvv0ZQv8s7a1lWAadTyvgbmo3cvX/KHfam5pGf2DFEXWIHZgvoIzq8GY6V4sjOEWRG2sAn+jKiNT5jPgG8sG0faP2JVr55WoN4jRthk5ABckyS8PByWrwcLILTeBPuX7DpiKtzUzzRw/qHAGo59+bFyZiKIc5I+S59fnttJ6Vz4jpjsavOzNsgIGUsTs3y1kosNLYoJVcI3RjpgHQuOfzawKb2l22B5wbJ1/1llhrSqYCtEjAhUuruB3bhy+/WiN4ulKp29Ct7/IEN3ctBXdMBm2xCPlsPSTBeXzwJNeWykTnpFx9qykjtSj3CwS8ZDnY3M+/dLhywrI46EGa03YRw=
#    on:
#      tags: true
#    edge: true
  - provider: releases
    token:
      secure: kWHX+ZVa4I+CGHKDYbSnuIYY2DoTbWsaxPAhONb2Iv0AIJE7TPN/RLxW1czMozYOS302SEpSKuOI7JR7akoV691ZWJFbSuQXeEWsosRZdruraf3hKQVGCLSexXKjCypkI4DRWPYOP1o+iExF3Et+JToY4IIdpeLOq12LGJctmytycFn3WAaaIcvW7eIbngPPt701r2zgDiW06POx6Tizuc/nPrhVk0ldfSSE8/+tMIFvTG1P6q2+VQ6z0tVIcZh+Q/4oVRI9bDncdep1q6aJYnAOK0ck9SN+EHu9VLwVXLjyKPZiO4bSaC9TDn9JqyrLb70MbPnJex6VnSRtJoE0yQ0qmtQeU32wba34mazatp+ze68oM6/UMOApoYC7I/DI7QlAB4ZzjrCQGrCcXLAjNkDHfZSgRaKxzx9ncSmgn3gQnSY0EnnTgEWJlstG4znreKnnBJOWUc/RoWQXbjgEoH3C7X0lpdnIOPhpnqaLoUhhinYAu69kpIVSJHbc6yrHH9COUA8aHLjQysQXtA3la7cozy2jdpUyQoiF5M8Vm3IbqUHCIYXbB50N0+DS5wrzNZwH2kvdQnTGFBAiuygQajmYatbnSuUDOUyYzpSftKu4PFtacFCWZwKOLNzotHLUjmo6qBu4J/uXbziIm/8p18i6ZzfPp4V+9k2K5tThSrk=
    file: dist/vip-report-template.html
    on:
      tags: true
    edge: true # opt in to dpl v2