os: linux
dist: jammy
language: node_js
env:
  - COREPACK_INTEGRITY_KEYS=0 # workaround for https://github.com/nodejs/corepack/issues/627
node_js:
  - 22
branches:
  only:
    - main
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
before_install:
  - corepack enable
  - corepack prepare pnpm@latest-9 --activate
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm install
script:
  - pnpm run lint
  - pnpm run coverage
  - pnpm run build
before_deploy:
  - cp dist/index.html dist/vip-report-template.html
deploy:
  - provider: script
    script: bash scripts/deploy_npm_registry.sh
    on:
      tags: true
  - provider: releases
    token:
      secure: rQ19Q5xN6T+dJp4nDT+B4QREJNCc9HpOdipE7jcAP/PVD49kd3AI4joZD9nBn53a091rl7VHviqzyRvHyvBI00VWGhQOmbUqd45c5h4Vn0qUZno2Wl2M7iuUyllvovQHS0C34nLDSBkKhJv0ESit/xiyyVy8JxwO1mgFcLgsY0cKiupwbhepUw5V2S458pNLW9e4RxT7RIaQWUagYp+PJYRKAYn5AAxih65mv2+wSGQPzcOKJDRSTlDtLaCrfZCNJm/7f3iSAOm1CCA1HLxNO2ACFL4bhnghWPS7O6VyTv1POexgwbH0OQxHmO/pdm3geLrTWX7PaHaZNUB1CHoNXC5FE/J9sUSrjClfGL9qFo5WEkBAgH3a5lLwUoCWZecUJPnyeIEFieg5OSjnXFrTECWo5Ut4g5RtzOWQtTLEwOXQgDBtE3NLkH/DRayO9vliEs9/6CnZ8AndH17cj/GmB//2DTjOMr3yCQVuI5ZeANBAUoXAg/C6kQDTdP8oyLay7UBJnX1aEWWLf3Gwo0UBFE83YIuzqVzIvU8HYgFiPgjxFwKBmebS4qu1n9ils2X0nWaY9KZY4lIjzkxsgsZ2pqt1Z6a5AQsEqXv06Tjy6tB7/I9TG7vl4eTBBJBPsRKMNnTfkE6Zr3oHC+ihWIMolAqyaTriOh23Gs/xzEuK+T8=
    file: dist/vip-report-template.html
    on:
      tags: true
    edge: true

